default_platform :ios

platform :ios do
	lane :beta do
		gym
		crashlytics
	end
end

platform :android do
	lane :beta do
		gradle(
			project_dir: "./android",
			task: "clean assembleRelease"
			
		)
		crashlytics
	end
end
